#ifndef BACKGAMMON_LOGIC_H
#define BACKGAMMON_LOGIC_H

/* Generated with cbindgen:0.6.1 */

/* WARNING:
 * This file is autogenerated by `cbindgen`. Don't modify this manually.
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

#define RUST_BOARD_SIZE 24

#define RUST_DIE_MAX 6

typedef struct RUST_Dice RUST_Dice;

typedef struct RUST_Player RUST_Player;

typedef struct RUST_Point RUST_Point;

typedef RUST_Point RUST__Board[BOARD_SIZE];

typedef struct
{
        RUST__Board board;
        uint8_t bar_black;
        uint8_t bar_white;
} RUST_Board;

typedef struct
{
        RUST_Board board;
        RUST_Dice dice;
        RUST_Player turn;
} RUST_Game;

RUST_Game init_game(void);

RUST_Player init_player(void);

int32_t rust_test_ffi(int32_t x);

#endif /* BACKGAMMON_LOGIC_H */
